#!/usr/bin/env ruby

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'tipi'

puts "tipi v#{Tipi::VERSION}"
puts Dir.pwd
puts

Dir.glob("lib/**/*.rb"){|lib| load lib}

api = Tipi::API.boot

case ARGV[0]
  when "spec" then api.generate_spec
  when "doc" then api.generate_doc
  else api.execute_tests
end
